ARG UBUNTU_VERSION=24.04
ARG CURL_VERSION=8.11.0
ARG QUICHE_VERSION=0.22.0
ARG BORINGSSL_TAG=OQS-BoringSSL-snapshot-2024-10
ARG LIBOQS_TAG=0.11.0

# Build Stage
FROM ubuntu:${UBUNTU_VERSION} AS build
ARG CURL_VERSION
ARG QUICHE_VERSION
ARG BORINGSSL_TAG
ARG LIBOQS_TAG

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake gcc ninja-build libunwind-dev \
    pkg-config build-essential \
    cargo git wget ca-certificates

# Cloning required repositories and downloading dependencies
WORKDIR /root
RUN git clone --branch ${BORINGSSL_TAG} --single-branch --depth 1 https://github.com/open-quantum-safe/boringssl.git bssl \
    && git clone --branch ${LIBOQS_TAG} --single-branch --depth 1 https://github.com/open-quantum-safe/liboqs.git liboqs \
    && git clone --recursive --depth 1 --branch ${QUICHE_VERSION} https://github.com/cloudflare/quiche quiche \
    && mkdir -p curl \
    && wget -O- "https://curl.se/download/curl-${CURL_VERSION}.tar.gz" | tar -xz --strip-components=1 -C curl


# Build and install liboqs
WORKDIR /root/liboqs/build
RUN cmake -G"Ninja"  \
    "-DCMAKE_INSTALL_PREFIX=../../bssl/oqs"  \
    "-DOQS_USE_OPENSSL=OFF" .. \
    && ninja -j"$(nproc)" && ninja install

# Build and insrtall BoringSSL
WORKDIR /root/bssl/build
RUN cmake -GNinja  \
    "-DCMAKE_BUILD_TYPE=Release" \
    "-DBUILD_SHARED_LIBS=1" .. \
    && ninja -j"$(nproc)" && ninja install \
    && cp -rp "../install/include" "/usr/local/include/bssl" \
    && cp -rp "../install/lib" "/usr/local/lib/bssl"

# Build quiche with custom BoringSSL integration, enabling HTTP/3 and QUIC support
WORKDIR /root/quiche/quiche/deps
RUN rm -R boringssl \
    && ln -s /root/bssl boringssl \
    && cd /root/quiche \
    && cargo build --package quiche --release --features ffi,pkg-config-meta,qlog \
    && cp -p target/release/libquiche.so /usr/local/lib/bssl/libquiche.so.0

# Build and install cURL
WORKDIR /root/curl
RUN LIBS=-lpthread ./configure \
    LDFLAGS=-Wl,-rpath,/usr/local/lib/bssl \
    --with-openssl=/root/bssl/install \
    --with-quiche=/root/quiche/target/release \
    --without-libpsl \
    --prefix=/usr/local/curl \
      && make -j$(nproc) && make install


# Final stage to include only necessary files
FROM ubuntu:${UBUNTU_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates


COPY --from=build /usr/local/include/bssl /usr/local/include/bssl
COPY --from=build /usr/local/lib/bssl /usr/local/lib/bssl
COPY --from=build /usr/local/curl /usr/local/curl

RUN ln -s /usr/local/curl/bin/curl /usr/local/bin/curl