name: Build & Test - curl

on:
  push:
    branches: [ 'main' ]
    paths: ['.github/workflows/curl.yml', 'curl/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['.github/workflows/curl.yml', 'curl/**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        build:
          - name: release
          - name: latest
            build-args: |
              LIBOQS_TAG=main
              OQSPROVIDER_TAG=main
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            ${{ matrix.build.build-args }}
          tags: oqs-curl

      - name: Build the Docker image (dev)
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            ${{ matrix.build.build-args }}
          target: dev
          tags: oqs-curl-dev

      - name: Spot-test - One baseline and one hybrid QSC alg
        run: |
          docker run -e TEST_TIME=5 -e KEM_ALG=kyber768 -e SIG_ALG=dilithium3 oqs-curl perftest.sh
