name: curl

on:
  push:
    branches: [ 'main' ]
    paths: ['.github/workflows/curl.yml', 'curl/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['.github/workflows/curl.yml', 'curl/**']
  workflow_call:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean

env:
  build-args: |
    LIBOQS_TAG=main
    OQSPROVIDER_TAG=main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-curl

      - name: Build the Docker image (dev)
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          target: dev
          tags: oqs-curl-dev

      - name: Build the Docker image (with generic liboqs)
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            LIBOQS_BUILD_DEFINES="-DOQS_OPT_TARGET=generic"
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-curl-generic

      - name: Test curl and curl generic
        run: |
          docker run -e TEST_TIME=5 -e KEM_ALG=kyber768 -e SIG_ALG=dilithium3 oqs-curl perftest.sh &&
          docker run -e TEST_TIME=5 -e KEM_ALG=kyber768 -e SIG_ALG=dilithium3 oqs-curl-generic perftest.sh
