name: mosquitto

on:
  push:
    branches: [ 'main' ]
    paths: ['.github/workflows/mosquitto.yml', 'mosquitto/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['.github/workflows/mosquitto.yml', 'mosquitto/**']
  workflow_call:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean

env:
  build-args: |
    LIBOQS_TAG=main
    OQSPROVIDER_TAG=main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: mosquitto
          platforms: ${{ matrix.platform }}
          build-args: |
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-mosquitto

      - name: Test mosquitto using local docker network
        run: |
          docker network create --subnet=192.168.0.0/16 mosquitto-test &&
          docker run --network mosquitto-test --ip 192.168.0.2 -it --rm --name oqs-mosquitto-broker -e "BROKER_IP=192.168.0.2" -e "EXAMPLE=broker-start.sh" -d oqs-mosquitto &&
          docker run --network mosquitto-test --ip 192.168.0.3 -it --rm --name oqs-mosquitto-subscriber -e "BROKER_IP=192.168.0.2" -e "SUB_IP=192.168.0.3" -e "EXAMPLE=subscriber-start.sh" -d oqs-mosquitto &&
          docker run --network mosquitto-test --ip 192.168.0.4 -it --rm --name oqs-mosquitto-publisher -e "BROKER_IP=192.168.0.2" -e "PUB_IP=192.168.0.4" -e "EXAMPLE=publisher-start.sh" -d oqs-mosquitto &&
          sleep 2 &&
          docker logs oqs-mosquitto-publisher | grep "Client_pub sending PUBLISH" &&
          docker logs oqs-mosquitto-subscriber | grep "Hello world"
