name: nginx

on:
  push:
    branches: [ 'main' ]
    paths: ['.github/workflows/nginx.yml', 'nginx/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['.github/workflows/nginx.yml', 'nginx/**']
  workflow_call:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean

env:
  build-args: |
    LIBOQS_TAG=main
    OQSPROVIDER_TAG=main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: nginx
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-nginx

      - name: Build the curl Docker image (with generic liboqs)
        uses: docker/build-push-action@v6
        with:
          load: true
          context: curl
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            LIBOQS_BUILD_DEFINES="-DOQS_OPT_TARGET=generic"
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-curl-generic

      - name: Test nginx with curl generic
        run: |
          docker network create nginx-test &&
          docker run --network nginx-test --detach --rm --name oqs-nginx oqs-nginx &&
          sleep 2 &&
          docker run --network nginx-test oqs-curl-generic curl -k https://oqs-nginx:4433
