name: openssh

on:
  push:
    branches: [ 'main' ]
    paths: ['.github/workflows/openssh.yml', 'openssh/**']
  pull_request:
    branches: [ 'main' ]
    paths: ['.github/workflows/openssh.yml', 'openssh/**']
  workflow_call:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      build_main:
        description: "Build using liboqs and oqsprovider main branches"
        required: false
        default: false
        type: boolean

env:
  build-args: |
    LIBOQS_TAG=main
    OQSPROVIDER_TAG=main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          load: true
          context: openssh
          platforms: ${{ matrix.platform }}
          build-args: |
            MAKE_DEFINES=-j4
            ${{ (github.event.inputs.build_main == 'true') && env.build-args || null }}
          tags: oqs-openssh

      - name: Test openssh
        run: |
          docker run --rm --name oqs-openssh oqs-openssh connect-test.sh
