ARG LIBOQS_TAG=main

FROM ubuntu:focal as builder

ARG LIBOQS_TAG

ENV TZ=Europe/Zurich
ENV DEBIAN_FRONTEND=noninteractive

# Update apt software 
RUN apt update

# Install prerequisites
RUN apt install git libz-dev libevent-dev cmake gcc ninja-build libunwind-dev pkg-config python3 python3-psutil golang-go -y

WORKDIR /opt

# Download openlitespeed repository
RUN git clone https://github.com/litespeedtech/openlitespeed.git 

COPY build.sh.patch /opt/
COPY build_bssl.sh.patch /opt/

# Apply patch to build.sh
RUN cd openlitespeed && git apply --reject --whitespace=fix /opt/build.sh.patch 


ENV LIBOQS_TAG=${LIBOQS_TAG}
# Build and install openlitespeed
RUN cd openlitespeed && ./build.sh &&  ./install.sh

WORKDIR /root/

# Configuring the server to expose CA.crt on port 80 and to enable QUIC on port 443
COPY httpd_config.conf /usr/local/lsws/conf/

FROM ubuntu:focal 

ENV TZ=Europe/Zurich
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=builder /usr/local/lsws/ /usr/local/lsws
COPY --from=builder /usr/local/lib/liboqs.* /usr/local/lib

RUN ldconfig

RUN apt update && apt install -y openssl net-tools
WORKDIR /root/

COPY serverstart.sh .
